//Must know:



/*
1-var, let, const (already practiced)
2- default parameter
3- template string
            3.1: create multi-line string (``)
            3.2: add dynamic variable (expression): `${}`
            4- arrow function
            4:1: single parameter arrow function
            4.2: tow parameter arrow function
            4:3: arrow function with function doby. and don't forget u have to return explicitly.
 5- spread operator[...numbers, 12, 45]
 6- destructuring
 7- map, filter, find




*/